version: '3.8'

services:
  efficore_redis:
    image: redis:7-alpine
    command: redis-server --port 6389 --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - efficore_redis_data:/data
    networks:
      - whatsapp_internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6389", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  core-api:
    image: docker.io/iamhuble/whatsapp-saas-core:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - CORE_API_PORT=4001
      - CORE_API_URL=http://core-api:4001
      - DATABASE_URL=postgresql://USUARIO:PASSWORD@HOST_POSTGRES:5432/NOMBRE_DB
      - SESSION_SECRET=CAMBIA_ESTO_POR_UN_SECRETO_LARGO_32_CARACTERES
      - WA_API_URL=http://whatsapp-api:4080
      - REDIS_URL=redis://efficore_redis:6389
      - MINIO_ENDPOINT=https://TU_MINIO_ENDPOINT
      - MINIO_ACCESS_KEY=TU_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=TU_MINIO_SECRET_KEY
      - MINIO_BUCKET=whatsapp-media
      - MINIO_PUBLIC_URL=https://TU_MINIO_PUBLIC_URL
      - STRIPE_SECRET_KEY=sk_live_TU_STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET=whsec_TU_STRIPE_WEBHOOK_SECRET
      - STRIPE_PRICE_WEEKLY_50=price_TU_STRIPE_PRICE_ID
      - FRONTEND_URL=https://app.efficore.es
      - SMTP_HOST=smtp.tuservidor.com
      - SMTP_PORT=587
      - SMTP_USER=correo@tudominio.com
      - SMTP_PASS=TU_SMTP_PASSWORD
      - SMTP_FROM_EMAIL=noreply@efficore.es
      - SMTP_FROM_NAME=EfficoreChat
      - OPENAI_API_KEY=sk-TU_OPENAI_API_KEY
      - OPENAI_MODEL=gpt-4o-mini
      - SUPER_ADMIN_USER=admin
      - SUPER_ADMIN_PASS=TU_SUPER_ADMIN_PASSWORD
    networks:
      - whatsapp_internal
      - traefik_public
    depends_on:
      - efficore_redis
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatsapp_core.rule=Host(`api.efficore.es`)"
        - "traefik.http.routers.whatsapp_core.entrypoints=websecure"
        - "traefik.http.routers.whatsapp_core.tls.certresolver=le"
        - "traefik.http.services.whatsapp_core.loadbalancer.server.port=4001"

  whatsapp-api:
    image: docker.io/iamhuble/whatsapp-saas-wa:latest
    environment:
      - NODE_ENV=production
      - PORT=4080
      - CORE_API_URL=http://core-api:4001
      - MINIO_ENDPOINT=https://TU_MINIO_ENDPOINT
      - MINIO_ACCESS_KEY=TU_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=TU_MINIO_SECRET_KEY
      - MINIO_BUCKET=whatsapp-media
      - MINIO_PUBLIC_URL=https://TU_MINIO_PUBLIC_URL
    volumes:
      - whatsapp_sessions:/app/src/storage/sessions
    networks:
      - whatsapp_internal
      - traefik_public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatsapp_wa.rule=Host(`wa.efficore.es`)"
        - "traefik.http.routers.whatsapp_wa.entrypoints=websecure"
        - "traefik.http.routers.whatsapp_wa.tls.certresolver=le"
        - "traefik.http.services.whatsapp_wa.loadbalancer.server.port=4080"

  frontend:
    image: docker.io/iamhuble/whatsapp-saas-frontend:latest
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CORE_API_URL=http://core-api:4001
    networks:
      - whatsapp_internal
      - traefik_public
    depends_on:
      - core-api
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)}).on('error', () => process.exit(1))"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatsapp_frontend.rule=Host(`app.efficore.es`)"
        - "traefik.http.routers.whatsapp_frontend.entrypoints=websecure"
        - "traefik.http.routers.whatsapp_frontend.tls.certresolver=le"
        - "traefik.http.routers.whatsapp_frontend.priority=100"
        - "traefik.http.services.whatsapp_frontend.loadbalancer.server.port=4000"
        - "traefik.http.services.whatsapp_frontend.loadbalancer.healthcheck.path=/"
        - "traefik.http.services.whatsapp_frontend.loadbalancer.healthcheck.interval=10s"

volumes:
  whatsapp_sessions:
    driver: local
  efficore_redis_data:
    driver: local

networks:
  whatsapp_internal:
    driver: overlay
    attachable: true
  traefik_public:
    external: true
