version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-whatsapp_saas}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-whatsapp_saas}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  core-api:
    image: ${REGISTRY}/whatsapp-saas-core:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - CORE_API_PORT=${CORE_API_PORT:-3001}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-whatsapp_saas}
      - SESSION_SECRET=${SESSION_SECRET:?SESSION_SECRET is required}
      - WA_API_URL=http://whatsapp-api:${WA_API_PORT:-8080}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    ports:
      - "${CORE_API_PORT:-3001}:${CORE_API_PORT:-3001}"
    networks:
      - internal
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${CORE_API_PORT:-3001}/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  whatsapp-api:
    image: ${REGISTRY}/whatsapp-saas-wa:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=${WA_API_PORT:-8080}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    ports:
      - "${WA_API_PORT:-8080}:${WA_API_PORT:-8080}"
    volumes:
      - whatsapp_sessions:/app/src/storage/sessions
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${WA_API_PORT:-8080}/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${REGISTRY}/whatsapp-saas-frontend:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=${FRONTEND_PORT:-3000}
      - CORE_API_URL=http://core-api:${CORE_API_PORT:-3001}
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    networks:
      - internal
    depends_on:
      - core-api
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${FRONTEND_PORT:-3000}/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  whatsapp_sessions:
    driver: local

networks:
  internal:
    driver: overlay
    attachable: true
