version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-whatsapp_saas}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-whatsapp_saas}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  core-api:
    image: ${REGISTRY}/whatsapp-saas-core:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - CORE_API_PORT=${CORE_API_PORT:-3001}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-whatsapp_saas}
      - SESSION_SECRET=${SESSION_SECRET:?SESSION_SECRET is required}
      - WA_API_URL=http://whatsapp-api:${WA_API_PORT:-8080}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    networks:
      - internal
      - traefik_public
    depends_on:
      - postgres
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatsapp_core.rule=Host(`${CORE_API_DOMAIN}`)"
        - "traefik.http.routers.whatsapp_core.entrypoints=websecure"
        - "traefik.http.routers.whatsapp_core.tls.certresolver=le"
        - "traefik.http.services.whatsapp_core.loadbalancer.server.port=${CORE_API_PORT:-3001}"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${CORE_API_PORT:-3001}/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  whatsapp-api:
    image: ${REGISTRY}/whatsapp-saas-wa:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=${WA_API_PORT:-8080}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    volumes:
      - whatsapp_sessions:/app/src/storage/sessions
    networks:
      - internal
      - traefik_public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatsapp_wa.rule=Host(`${WA_API_DOMAIN}`)"
        - "traefik.http.routers.whatsapp_wa.entrypoints=websecure"
        - "traefik.http.routers.whatsapp_wa.tls.certresolver=le"
        - "traefik.http.services.whatsapp_wa.loadbalancer.server.port=${WA_API_PORT:-8080}"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${WA_API_PORT:-8080}/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${REGISTRY}/whatsapp-saas-frontend:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=${FRONTEND_PORT:-3000}
      - CORE_API_URL=http://core-api:${CORE_API_PORT:-3001}
    networks:
      - internal
      - traefik_public
    depends_on:
      - core-api
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatsapp_frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
        - "traefik.http.routers.whatsapp_frontend.entrypoints=websecure"
        - "traefik.http.routers.whatsapp_frontend.tls.certresolver=le"
        - "traefik.http.services.whatsapp_frontend.loadbalancer.server.port=${FRONTEND_PORT:-3000}"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${FRONTEND_PORT:-3000}/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  whatsapp_sessions:
    driver: local

networks:
  internal:
    driver: overlay
    attachable: true
  traefik_public:
    external: true
