version: '3.8'

services:
  whatsapp-api:
    image: ${REGISTRY:-localhost:5000}/whatsapp-api:${TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    volumes:
      - whatsapp_sessions:/app/src/storage/sessions
      - whatsapp_data:/app/src/storage
    networks:
      - whatsapp-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.whatsapp-api.rule=Host(`whatsapp-api.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.whatsapp-api.entrypoints=websecure"
        - "traefik.http.routers.whatsapp-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.whatsapp-api.loadbalancer.server.port=5000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp_sessions:
    driver: local
  whatsapp_data:
    driver: local

networks:
  whatsapp-network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
